# services 실행할 서비스를 정의
# 띄어쓰기 등 정확해야 실행이 된다.
services:
# postgres: 우리가 정해주는 이름
  postgres:
    image: postgres:15
    restart: always
    # volumes: docker 종료시 원하는 경로에 데이터를 남겨줌
    # : 을 기준으로 왼쪽은 현 경로 우측은 docker 이미지 경로
    # local:docer 싱크를 맞춤
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
